# Generated by Django 2.0 on 2017-12-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171221_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
