# Generated by Django 2.0 on 2017-12-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171221_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
