# Generated by Django 2.0 on 2017-12-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171221_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='affiliated_links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linktype', models.IntegerField(choices=[(1, 'Books'), (2, 'Group'), (3, 'Recommended'), (4, 'Grow')], default=1)),
                ('image_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('text_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated', 'name', 'linktype'],
            },
        ),
    ]
