# Generated by Django 2.0 on 2017-12-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_affiliated_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliated_links',
            name='item_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
