# Generated by Django 2.0 on 2017-12-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_affiliated_links_item_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliated_links',
            name='image_url',
            field=models.CharField(blank=True, help_text='enter the image with a tag', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='affiliated_links',
            name='item_url',
            field=models.CharField(blank=True, help_text="enter the item's amazon link url", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='affiliated_links',
            name='name',
            field=models.CharField(blank=True, help_text='The name you want to call', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='affiliated_links',
            name='text_url',
            field=models.CharField(blank=True, help_text='enter the text  with a tag', max_length=1000, null=True),
        ),
    ]
