# Generated by Django 2.0 on 2017-12-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171221_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliated_links',
            options={'ordering': ['-timestamp', '-updated', 'name', 'linktype'], 'verbose_name': 'Affiliated Link', 'verbose_name_plural': 'Affiliated Links'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-timestamp', '-updated'], 'verbose_name': 'Price', 'verbose_name_plural': 'Prices'},
        ),
        migrations.AlterField(
            model_name='affiliated_links',
            name='image_url',
            field=models.URLField(blank=True, help_text='enter the image with a tag', max_length=1000, null=True),
        ),
    ]
