# Generated by Django 2.0 on 2017-12-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171221_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliated_links',
            name='image_url',
            field=models.CharField(blank=True, help_text='enter the image with a tag', max_length=1000, null=True),
        ),
    ]
