# Generated by Django 2.0 on 2017-12-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171221_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliated_links',
            old_name='image_url',
            new_name='href_one',
        ),
        migrations.RenameField(
            model_name='affiliated_links',
            old_name='text_url',
            new_name='src_one',
        ),
        migrations.RenameField(
            model_name='affiliated_links',
            old_name='item_url',
            new_name='src_two',
        ),
    ]
