# Generated by Django 2.0 on 2017-12-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20171221_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliated_links',
            name='purchase_rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
