# Generated by Django 2.0 on 2017-12-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_affiliated_links_purchase_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliated_links',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
